jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: cypress-io/github-action@v6
      - run: make setup
      - run: make test
      - run: make lint
